import type { Metadata } from "next";
import { Inter, Itim } from "next/font/google";

import "./globals.css";
import { NavBar } from "./components/nav";
import { FooterModule } from "./components/footer";
import { Toaster } from "sonner";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-inter",
});

const itim = Itim({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-itim",
});

export const metadata: Metadata = {
  title: "Olamilekan Akanni's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${itim.variable} antialiased bg-[#080808]`}
      >
        <Toaster position="top-right" richColors />
        <NavBar />
        <main className="flex-grow">{children}</main>
        <FooterModule />
      </body>
    </html>
  );
}
